services:
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    networks:
      - doc_processing_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 30s
      timeout: 10s
      retries: 3

  spacy:
    image: jgontrum/spacyapi:latest
    container_name: spacy
    ports:
      - "8080:80"
    networks:
      - doc_processing_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  doc_processing_network:
    name: doc_processing_network
    driver: bridge