version: '3.8'

services:
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    networks:
      - doc_processing_network
    restart: unless-stopped

  spacy:
    image: jgontrum/spacyapi:latest
    container_name: spacy
    ports:
      - "8080:80"
    networks:
      - doc_processing_network
    restart: unless-stopped

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    volumes:
      - ./document_processor/uploads:/app/document_processor/uploads
      - ./document_processor/results:/app/document_processor/results
    depends_on:
      - tika
      - spacy
    networks:
      - doc_processing_network

networks:
  doc_processing_network:
    driver: bridge